environment:
  matrix:
  - TARGET: x86_64-pc-windows-msvc
  - TARGET: i686-pc-windows-msvc
install:
  - curl https://win.rustup.rs/ > rustup-init.exe
  - rustup-init.exe -y --default-host %TARGET%
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - set CARGO_TARGET_DIR=%APPVEYOR_BUILD_FOLDER%\target
  - rustc -V
  - cargo -V

build_script:
  - cargo build --release

artifacts:
  - path: target/release/git-submerge.exe
    name: git-submerge
