language: rust
sudo: false
dist: trusty
matrix:
  include:
    - rust: 1.15.0
      os: linux
    - rust: 1.16.0
      os: linux
    - rust: 1.17.0
      os: linux
    - rust: 1.18.0
      os: linux
    - rust: stable
      os: linux
    - rust: beta
      os: linux
    - rust: nightly
      os: linux
    - rust: stable
      os: osx
    - rust: beta
      os: osx
    - rust: nightly
      os: osx
cache:
 directories:
  - $HOME/.cargo
script:
  - cargo build
